# Discord Webhook Configuration
# Создай webhook в Discord канале: Настройки канала → Интеграции → Вебхуки → Создать вебхук
# Скопируй URL вебхука и вставь сюда

webhook.url=https://discord.com/api/webhooks/1495042413159256235/n4rLx3pi4IV72heanh7SN6T0kbjMc8JRC6s9yD_SHQL_4v1qGljij8lam60ILZTAsX-Y
webhook.enabled=true
